### ISSUE TITLE
fluentd metrics are not shown on Prometheus

### ISSUE THREAD

**Issue by socialfeels** [kazegusuri/fluent-plugin-prometheus#28]
Hello kazegusuri, 
I am trying to run fluent-plugin-prometheus on k8s,  I see fluentd pod on k8s targets, It is up. but I couldn't see any metrics related **docker_command_log** to execute on prometheus. Please, can you help this issue?
Please find my files in below.

Thanks, 

Dockerfile:
```
FROM fluent/fluentd:v0.12-onbuild

USER root

RUN apk add --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install \
        fluent-plugin-rewrite-tag-filter:1.5.6 \
        fluent-plugin-parser:0.6.1 \
        fluent-plugin-prometheus:0.3.0 \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem

# listen port 24224 for Fluentd forward protocol
EXPOSE 24224
# prometheus plugin expose metrics at 0.0.0.0:24231/metrics
EXPOSE 24231
```
fluent.conf
```
<source>
  @type forward
</source>
<source>
  @type prometheus
</source>

<filter docker.**>
  @type prometheus
  <metric>
    name docker_command_log
    type counter
    desc total docker commands
    #key log
  </metric>
</filter>

<match docker.**>
  @type copy
  <store>
    @type stdout
  </store>
</match>
```
k8s-development.yaml

```
...
apiVersion: v1
kind: Deployment
metadata:
  name: fluentd
spec:
  template:
    metadata:
      labels:
        app: fluentd
      name: fluentd
    spec:
      containers:
      - image: myimage
        name: fluentd
        ports:
        - containerPort: 24231
          hostPort: 24231
```
prometheus.yml
```
...
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
         - targets: ['localhost:9090','fluentd:24231']
```
